name: swipe_animation
description: Prototype swipe animation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  iconsax: ^0.0.8
  cached_network_image: ^3.3.0
  youtube_player_iframe: ^4.0.4
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/joker.jpeg
    - lib/assets/images/taxi.jpeg
    - lib/assets/images/tgf.jpeg
    - lib/assets/images/default.jpeg
    - lib/assets/images/success.json
    - lib/assets/json/cinema.json